# drivers/video/mtk/Makefile
#
# Makefile for MT6516 video driver.
#

ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/hdmitx/  \
             -I$(MTK_PATH_SOURCE)/drivers/hdmitx/	\
			 -I$(MTK_PATH_PLATFORM)/drivers/video/  \
             -I$(MTK_PATH_SOURCE)/drivers/video/	\
               -I$(MTK_PATH_PLATFORM)/drivers/hdmitx/  \
             	-I$(MTK_PATH_SOURCE)/drivers/hdmitx/	\


obj-y	:= hdmitx.o debug.o




