#
# Makefile for the Linux Bluetooth HCI device drivers.
#
ccflags-y := -I$(src)/include -I$(src)/../common/include -I$(src)/../common/linux/include 

obj-m += hci_stp.o
hci_stp-objs	:= linux/hci_stp.o
 
