/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2011.
 * Fri Jul  6 15:32:04 2012
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_HF_MIC_CHANNEL     1
#define AUXADC_UTMS_CHANNEL     2
#define AUXADC_TEMPERATURE_CHANNEL     3


#endif //_CUST_AUXADC_TOOL_H


