/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2011.
 * Fri Jul  6 15:32:04 2012
 * Do Not Modify the File.
 */



#include <mach/upmu_sw.h>


//****for customer use*******// 


//PMIC default enable/disable result

//PMIC mode select 
typedef enum
{
   BY_ENABLE = 0,
   BY_SRCLKEN = 1
}MODE_sel_enum;

////For Common use 

//For PMIC driver use




